import argparse
import sys

DESCRIPTION = "Get the git-log csv generated by Zak's script and process it a bit more"
parser = argparse.ArgumentParser(description=DESCRIPTION)

parser.add_argument(
    "-s", "--source", help="""Input CSV file"""
)

parser.add_argument(
    "-o", "--output", default=None, help="""Output CSV file"""
)

def process(source, output):
    csv = []
    with open(source) as f:
        content = f.readlines()
        content = [x.strip() for x in content]
        csv.append(content[0])
        for l in content[1:]:
            tokens = l.split(',')
            if len(tokens[2].split('@')) > 1:
                tokens.insert(2, 'No Organization')

            if tokens[2] == '' or tokens[2] == 'Unknown':
                tokens[2] = 'No Organization'

            csv.append(','.join(tokens))

    if not output:
        print('\n'.join(csv))
        return

    with open(output, "w") as ff:
        ff.write('\n'.join(csv))

def main():
    args = parser.parse_args(sys.argv[1:])
    process(args.source, args.output)

if __name__ == "__main__":
    main()
