#!/bin/bash
#
#  Copyright (c) 2016 MariaDB Corporation
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA */

# Unload existing .plist, and stop running MariaDB Server
launchctl unload /Library/LaunchDaemons/com.mariadb.server.plist

mkdir -p /usr/local/mariadb

symlinks=( /usr/local/mariadb/server )

# Go through the symlinks in the array and, for each one, move it to use an unused suffixed
for dest in "${symlinks[@]}"
do
    if [[ -L $dest ]]
    then
        rm "$dest"
    elif [[ -e $dest ]]
    then
        # look for an unused suffix to rename $dest
        suffix=0
        while [[ -e $dest.$((++suffix)) ]]; do :; done

        mv "$dest" "$dest.$suffix"
    fi
done

