#!/usr/bin/env bash

set -o nounset
set -o pipefail

err() {
  echo >&2 "ERROR: $*"
  exit 1
}

usage() {
  cat >&2 <<-EOF
  Usage : $0
    -s also record sound
    -h help
EOF
}

typeset VAR_OPTIONAL_ARGS=""

while getopts "hs" OPTION; do
  case $OPTION in
    s)
      VAR_OPTIONAL_ARGS="with-sound"
      ;;
    h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

typeset -r OUTPUT="$HOME/screenrecord_$(date +'%Y-%m-%dT%H:%M:%S').mkv"

# necessary commands
for cmd in slop ffmpeg; do
  command -v $cmd >/dev/null || err "$cmd not found"
done

# get the area for recording from slop
read -p "Select zone to capture" \
  -r XOFFSET YOFFSET WEIGHT HIGHT < <(slop -f "%x %y %w %h")

# see https://trac.ffmpeg.org/wiki/Capture/Desktop
if [[ $VAR_OPTIONAL_ARGS == "with-sound" ]]; then
  ffmpeg \
    -video_size "${WEIGHT}x${HIGHT}" \
    -framerate 25 \
    -f x11grab \
    -i :0.0+"$XOFFSET","$YOFFSET" \
    -f pulse -ac 2 -i default \
    "$OUTPUT" || err "ffmpeg encoding"
else
  ffmpeg \
    -video_size "${WEIGHT}x${HIGHT}" \
    -framerate 25 \
    -f x11grab \
    -i :0.0+"$XOFFSET","$YOFFSET" \
    "$OUTPUT" || err "ffmpeg encoding"
fi
