# Configuration file for host: lu0012
# 
# OS: Ubuntu 9.10
# Platform: x86_64
# CPU: Dual-core Intel Core 2 Duo @ 2.80GHz
# RAM: 4GB
# Disk(s): 1 x HITACHI HTS722016K9SA00 S-ATA

#
# Adjust the following paths according to your installation.
#

# We need sysbench >= v0.5.
SYSBENCH='/usr/local/bin/sysbench'

# We need bzr >= 1.18.1
BZR='/usr/bin/bzr'

# OProfile binaries.
OPCONTROL='/usr/bin/opcontrol'

# System statistic binaries.
IOSTAT='/usr/bin/iostat'
IOSTAT_DEVICE='/dev/sda'
SAR='/usr/bin/sar'
