version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-source
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_DATABASE=db_maria
    volumes:
      - ./mariadb_data:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ['CMD', "healthcheck.sh", "--connect"]

  mysql:
    image: mysql:latest
    container_name: mysql-source
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=db_mysql
    volumes:
      - ./mysql_data:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ['CMD', "mysqladmin", "--password=", "--protocol", "tcp", "ping"]

  oracle:
    image: oracle/database:18.4.0-xe
    container_name: oracle-source
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=oracle
    volumes:
      - ./oracle_data:/opt/oracle/scripts/startup
    healthcheck:
      # test: ['CMD', "$ORACLE_BASE/$CHECK_DB_FILE >/dev/null || exit 1"]
      # test: ['CMD', "sqlplus", "-L", "system/oracle@//localhost:1521/XE", "@healthcheck.sql"]
      test: ['CMD',"/opt/oracle/checkDBStatus.sh"]
      start_period: 5m
      interval: 2m
      timeout: 30s
      retries: 5

  jdbc_target:
    build:
      context: .
      args:
        mariadb_version: "latest"
      dockerfile: ./Dockerfile
    container_name: mariadb-target
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_DATABASE=test
    volumes:
      - ./target_data/:/docker-entrypoint-initdb.d:z
      - ./target_conf/:/etc/mysql/conf.d/:z

    depends_on:
      mariadb:
        condition: service_healthy
      mysql:
        condition: service_healthy
      oracle:
        condition: service_healthy