#!/bin/bash
#===============================================================================
#
#          FILE: github-release-template
# 
#         USAGE: ./github-release-template
# 
#   DESCRIPTION: This script outputs instructions and suggested text for the
#                fields used in drafting a MariaDB release on GitHub
# 
#        AUTHOR: Daniel Bartholomew (dbart), dbart'at'mariadb(dot)com
#       CREATED: 12/12/2024 17:06
#===============================================================================

umask 002


set -eu
  # -e  Exit immediately if a simple command exits with a non-zero status,
  #     unless the command that fails is part of an until or  while loop, part
  #     of an if statement, part of a && or || list, or if the command's return
  #     status is being inverted using !.  -o errexit
  #
  # -u  Treat unset variables as an error when performing parameter expansion.
  #     An error message will be written to the standard error, and a
  #     non-interactive shell will exit.
  #
  # -x  Print a trace of simple commands and their arguments after they are
  #     expanded and before they are executed.

#-------------------------------------------------------------------------------
#  Variables
#-------------------------------------------------------------------------------
product=${1}
branch=${2}
ver=${3}

case ${ver} in
  v*) # Connectors releases versions sometimes start with 'v', remove it
    version="${ver:1}"
    ;;
  *) # Copy over in full if it doesn't start with 'v'
    version="${ver}"
    ;;
esac

# set location of prep.conf and prep.log to XDG-compatible directories
dir_conf=${XDG_CONFIG_HOME:-~/.config}
dir_log=${XDG_DATA_HOME:-~/.local/share}

#-------------------------------------------------------------------------------
# Functions
#-------------------------------------------------------------------------------

loadDefaults() {
  # Load the paths (if they exist)
  if [ -f ${dir_conf}/prep.conf ]; then
      . ${dir_conf}/prep.conf
  else
    echo
    echo "ERROR: ${dir_conf}/prep.conf preferences file not found"
    echo "Exiting..."
    exit 1
  fi
  if [ -f ${dir_conf}/common ]; then
      . ${dir_conf}/common
  else
    echo "ERROR: ${dir_conf}/common functions file not found"
    echo "Exiting..."
    exit 2
  fi
}

#-------------------------------------------------------------------------------
# Main Script
#-------------------------------------------------------------------------------

loadDefaults

case ${product} in
  galera )
    title='MariaDB Galera'
    gh_path="MariaDB/${product}"
    gh_tag="mariadb-${ver}"
    kb_slug=''
    ;;
  server )
    title='MariaDB Community Server'
    gh_path="MariaDB/${product}"
    gh_tag="mariadb-${ver}"
    kb_slug="community-server"
    ;;
  connector-c )
    title='MariaDB Connector/C'
    gh_path="mariadb-corporation/mariadb-${product}"
    gh_tag="${ver}"
    kb_slug="connectors/c"
    ;;
  connector-cpp )
    title='MariaDB Connector/C++'
    gh_path="mariadb-corporation/mariadb-${product}"
    gh_tag="${ver}"
    kb_slug="mariadb-${product}"
    ;;
  connector-odbc )
    title='MariaDB Connector/ODBC'
    gh_path="mariadb-corporation/mariadb-${product}"
    gh_tag="${ver}"
    kb_slug="mariadb-${product}"
    ;;
  connector-python )
    title='MariaDB Connector/Python'
    gh_path="mariadb-corporation/mariadb-${product}"
    gh_tag="${ver}"
    kb_slug="connectors/python/mariadb-connector-python-1-1-release-notes/mariadb-connector-python"
    ;;
esac

THICKLINE
MSG_L "Go to the following URI and click on 'Create release from tag'"
MSG_L ""
MSG_L "https://github.com/${gh_path}/releases/tag/${gh_tag}"
MSG_L ""
MSG_L "Fill in the field(s) as follows"
MSG_L ""
MSG "Release Title:"
echo
echo "${title} ${version}"
echo

case ${product} in
  server|connector-c|connector-odbc|connector-cpp|connector-python)
    MSG "Release Description:"
    echo
    #echo "Details on this release can be found in the [Release Notes](https://mariadb.com/docs/release-notes/${kb_slug}/${version//./-})"
    parts=(${version//./ })
    echo "Details on this release can be found in the [Release Notes](https://mariadb.com/docs/release-notes/${kb_slug}/${parts[0]}.${parts[1]}/${version})"
    echo
    ;;
esac

MSG "If the release is not a Stable (GA) release, check 'Set as a pre-release'"
MSG_L "Click 'Publish release'"
THICKLINE

