#!/bin/bash - 
#===============================================================================
#
#          FILE:  prep-c
# 
#         USAGE:  ./prep-c <version> <build_dir>
# 
#   DESCRIPTION:  This script is used to prepare files for a MariaDB
#                 Connector/C release
# 
#        AUTHOR: Daniel Bartholomew
#       CREATED: 17/05/23 00:56:37 EST
#===============================================================================


#-------------------------------------------------------------------------------
#  Variables
#-------------------------------------------------------------------------------
version=${1}
dir_build=${2}

dir_name="connector-c-${version}"

# set location of prep.conf and prep.log to XDG-compatible directories and then
# create them if they don't exist
dir_conf=${XDG_CONFIG_HOME:-~/.config}
dir_log=${XDG_DATA_HOME:-~/.local/share}


#-------------------------------------------------------------------------------
#  Functions
#-------------------------------------------------------------------------------

sumgen() {
  for sum in md5 sha1 sha256 sha512;do
	echo;LINE;echo ${sum};
	${sum}sum ./mar* >> ${sum}sums.txt
	${sum}sum -c ${sum}sums.txt
  done
  DIV
}

userResponse() {
  question="${@}"
  read -p "${question} " -n 1
  echo
  ANSWER=${REPLY}
  RESPONSE=${REPLY}
  return 0
}

loadDefaults() {
  # Load the paths (if they exist)
  if [ -f ${dir_conf}/prep.conf ]; then
      . ${dir_conf}/prep.conf
  else
    echo
    echo "The file ${dir_conf}/prep.conf does not exist in your home."
    echo "The prep script creates a default template of this file when run."
    echo "Exiting..."
    exit 1
  fi
}

usage() {
  echo
  echo "usage: $0 <version> <build_dir>"
  echo
  exit 1
}


DIV() { echo;echo;LINE;echo;echo;}
LINE() { echo -n '#';for i in {1..77} ; do echo -n '-';done;echo '-';}
THICKLINE() { echo -n '#';for i in {1..77} ; do echo -n '=';done;echo '=';}
RC() { echo "+ ${@}";if ${@};then return 0;else return 1;fi;}
PAUSE() { echo;read -p "Press any key to continue." -n 1;echo;return 0;}

MSG() { LINE;echo "# ${@}";LINE;}
MSG_I() { echo;echo;THICKLINE;echo "# ${@}";THICKLINE;}
MSG_L() { echo "# ${@}";}


shouldI() {
  local cont
  cont=""
   while [ -z ${cont} ]; do
     userResponse "Should I ${@//_/ }? [y/n]"
     case ${ANSWER} in
      "y")
        ${@}
        cont="yes"
        return 0
        ;;
      "n")
        echo "Skipping . . . "
        cont="yes"
        return 0
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        cont=""
        ;;
    esac
  done
}

copy_and_stage_files() {
  MSG "Copying and staging files"
  pushd ${cc_home}
    if [[ ! -d "${dir_name}" ]];then
      mkdir -v ${dir_name}
    fi
    for dir in ${dir_build}/*;do
      echo ${dir}
      case $(basename ${dir}) in 
        cc-centos7-amd64)
          cp -avi ${dir}/*.gz ${dir_name}/
          cp -avi ${dir}/*.zip ${dir_name}/
          ;;
        linux_x86-connector_c)
          cp -avi ${dir}/*.gz ${dir_name}/
          cp -avi ${dir}/*.zip ${dir_name}/
          ;;
        linux_x64-connector_c)
          cp -avi ${dir}/*amd64.tar.gz ${dir_name}/
          ;;
        cc-*-amd64)
          cp -avi ${dir}/*amd64.tar.gz ${dir_name}/
          ;;
        cc-*-x86)
          cp -avi ${dir}/*i386.tar.gz ${dir_name}/
          ;;
        win-connector_c_3)
          echo
          cp -avi ${dir}/*.msi ${dir_name}/
          ;;
        freebsd11_x64-connector_c)
          cp -avi ${dir}/*amd64.tar.gz ${dir_name}/
          ;;
        freebsd11_x86-connector_c)
          cp -avi ${dir}/*i386.tar.gz ${dir_name}/
          ;;
        *)
          MSG_I "+ fail: ${dir}"
          ;;
      esac
    done
    tree ${dir_name}/
  popd
  echo;echo;echo
}

prep_org_files() {
  # Prep .org files
  MSG "Prepping org files"
  if [[ ! -d "${cc_home_org}/${dir_name}" ]];then
    mkdir -v ${cc_home_org}/${dir_name}
  fi
  cp -avi ${cc_home}/${dir_name}/*src* ${cc_home_org}/${dir_name}/
  pushd ${cc_home_org}/${dir_name}
    sumgen
    for file in *;do
      echo "+ gpg ${gpg_opts} ${file}"
              gpg ${gpg_opts} ${file}
    done
  popd
  echo;echo;echo
}

update_org_current_to_this_release() {
  if [[ -d ${cc_home_org}/connector-c-current ]]; then
    rm -rf ${cc_home_org}/connector-c-current
  fi
  MSG "Updating current org release to this one..."
  set -x
  mkdir ${cc_home_org}/connector-c-current
  cp -avi ${cc_home}/${dir_name}/*src.tar.gz ${cc_home_org}/connector-c-current/mariadb-connector-c-current-src.tar.gz
  cp -avi ${cc_home}/${dir_name}/*src.zip ${cc_home_org}/connector-c-current/mariadb-connector-c-current-src.zip
  pushd ${cc_home_org}/connector-c-current/
  set +x
  sumgen
  for file in *;do
    echo "+ gpg ${gpg_opts} ${file}"
            gpg ${gpg_opts} ${file}
  done
  popd
  set +x
  echo;echo;echo
}

prep_com_files() {
  # Prep .com files
  MSG "Prepping com files"
  pushd ${cc_home}/${dir_name}
    sumgen
    for file in *;do
      echo "+ gpg ${ent_gpg_opts} ${file}"
              gpg ${ent_gpg_opts} ${file}
    done
  popd
  echo;echo;echo
}

upload_to_the_primary_mirror() {
  local upload
  upload=""
  echo;echo;echo;
  MSG "Doing a dry-run..."
  echo "+ rsync --dry-run -av --delete-after ${cc_home_org}/${dir_name} ${cc_home_org}/connector-c-current ${primary_mirror}:data/"
          rsync --dry-run -av --delete-after ${cc_home_org}/${dir_name} ${cc_home_org}/connector-c-current ${primary_mirror}:data/
  echo;echo;echo
  while [ -z ${upload} ]; do
    userResponse "Does the above look OK? [y/n]"
    case ${ANSWER} in
      "y")
        echo "+ rsync -av --delete-after ${cc_home_org}/${dir_name} ${cc_home_org}/connector-c-current ${primary_mirror}:data/"
                rsync -av --delete-after ${cc_home_org}/${dir_name} ${cc_home_org}/connector-c-current ${primary_mirror}:data/
        echo;echo;echo
        upload="yes"
        return 0
        ;;
      "n")
        echo "Something went wrong..."
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}

upload_to_the_corp_mirror_staging_dir() {
  local upload
  upload=""
  echo;echo;echo;
  MSG "Doing a dry-run..."
  echo "+ rsync --dry-run -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp_staging}/"
          rsync --dry-run -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp_staging}/
  echo;echo;echo
  while [ -z ${upload} ]; do
    userResponse "Does the above look OK? [y/n]"
    case ${ANSWER} in
      "y")
        echo "+ rsync -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp_staging}/"
                rsync -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp_staging}/
        echo;echo;echo
        upload="yes"
        return 0
        ;;
      "n")
        echo "Something went wrong..."
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}


upload_to_the_corp_mirror() {
  local upload
  upload=""
  echo;echo;echo;
  MSG "Doing a dry-run..."
  echo "+ rsync --dry-run -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp}/"
          rsync --dry-run -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp}/
  echo;echo;echo
  while [ -z ${upload} ]; do
    userResponse "Does the above look OK? [y/n]"
    case ${ANSWER} in
      "y")
        echo "+ rsync -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp}/"
                rsync -av --delete-after ${cc_home}/${dir_name} ${cc_home_corp}/
        echo;echo;echo
        upload="yes"
        return 0
        ;;
      "n")
        echo "Something went wrong..."
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}

#===  FUNCTION  ================================================================
#          NAME:  generate_the_file_list_pickle_for_org_downloads
#   DESCRIPTION:  This function logs in to the primary mirror and runs the
#                 command to generate the pickle that is then imported into the
#                 mariadb.org downloads system.
#===============================================================================
generate_the_file_list_pickle_for_org_downloads() {
  ssh -t -t ${primary_mirror} "set -x; python generate_file_list.py data/ --release=${dir_name}";
}

#===  FUNCTION  ================================================================
#          NAME:  update_the_STATUS_file
#   DESCRIPTION:  Simple function to update a STATUS file with a UNIX timestamp
#===============================================================================
update_the_STATUS_file() {
  echo "+ date +%s > ${cc_home_org}/STATUS"
          date +%s > ${cc_home_org}/STATUS
  MSG "STATUS file updated"
}

#===  FUNCTION  ================================================================
#          NAME:  uploader
#   DESCRIPTION:  Upload a release
#===============================================================================
uploader() {
  local dest
  local dests
  local rsync_uploader_opts
  dests="$@"
  rsync_uploader_opts="-av --delete-before --exclude=TIME --exclude=exclude --exclude=*orig"
  for dest in ${dests} ; do
    local cont
    cont=""
    while [ -z ${cont} ]; do
      userResponse "Should I upload to ${dest}? [y/n]"
      case ${ANSWER} in
        y)
          MSG "Uploading to ${dest}..."
          case ${dest} in
            *hz-archive*)
              rsync_uploader_opts="${rsync_uploader_opts} --no-group --no-owner --no-perms"
              ;;
          esac
          rsync_wrapper "${rsync_uploader_opts} ${cc_home_org}/${dir_name} ${dest}/"
          rsync_wrapper "${rsync_uploader_opts} ${cc_home_org}/connector-c-current ${dest}/"
          cont="yes"
          ANSWER=""
          ;;
        n)
          MSG "Skipping uploading to ${dest}..."
          cont="yes"
          ANSWER=""
          ;;
        *)
          MSG_L "Please answer [y]es or [n]o."
          cont=""
          ANSWER=""
          ;;
      esac
    done
  done
}

# Wrapper functions for uploader
upload_to_the_mirrors() {
  uploader "${mirrors}"
}

upload_to_the_archives() {
  uploader "${archives}"
}

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  rsync_wrapper
#   DESCRIPTION:  This function provides a safety net for using rsync. It takes
#                 the options part of the rsync (everything that would come
#                 after the rsync command itself on the command-line) and first
#                 runs it with the --dry-run flag. It then asks if everything
#                 is OK. Assuming things are OK, it runs the rsync for real.
#-------------------------------------------------------------------------------
rsync_wrapper() {
  local upload
  upload=""
  rsync_body="${@}"
  MSG_L "Doing a dry run..."
  RC rsync --dry-run ${rsync_body} | less
  echo
  while [ -z ${upload} ]; do
    userResponse "Did the dry run look OK? [y/n]"
    case ${ANSWER} in
      "y")
        MSG_L "Transferring for real..."
        RC rsync ${rsync_body}
        echo
        upload="yes"
        ANSWER=""
        return 0
        ;;
      "n")
        MSG_L "Something went wrong..."
        ANSWER=""
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}


#-------------------------------------------------------------------------------
# Main Script
#-------------------------------------------------------------------------------

loadDefaults

if [ "${version}" = "" ]; then
  usage
fi

if [ "${dir_build}" = "" ]; then
  usage
fi

set -eu
  # -e  Exit immediately if a simple command exits with a non-zero status,
  #     unless the command that fails is part of an until or  while loop, part
  #     of an if statement, part of a && or || list, or if the command's return
  #     status is being inverted using !.  -o errexit
  #
  # -u  Treat unset variables as an error when performing parameter expansion.
  #     An error message will be written to the standard error, and a
  #     non-interactive shell will exit.
  #
  # -x  Print a trace of simple commands and their arguments after they are
  #     expanded and before they are executed.

MSG_I "Preparing MariaDB Connector/C ${version} release..."

shouldI copy_and_stage_files
echo;echo
shouldI prep_org_files
echo;echo
shouldI update_org_current_to_this_release
echo;echo
shouldI prep_com_files
echo;echo
shouldI upload_to_the_corp_mirror_staging_dir
echo;echo

MSG_I "Mirrors"
for mirror in ${mirrors} ; do echo "- ${mirror}";done;echo
shouldI upload_to_the_mirrors
echo;echo
MSG_I "Archives"
for archive in ${archives} ; do echo "- ${archive}";done;echo
shouldI upload_to_the_archives



echo;echo
shouldI upload_to_the_primary_mirror
echo;echo
shouldI upload_to_the_corp_mirror
echo;echo
shouldI generate_the_file_list_pickle_for_org_downloads
echo;echo
shouldI update_the_STATUS_file
MSG_I "All done!"
LINE;LINE;LINE
echo;echo;echo

