#!/bin/bash - 
#===============================================================================
#
#          FILE:  prep-shared-rpms
# 
#         USAGE:  ./prep-shared-rpms
# 
#===============================================================================

version=$1

usage() {
  echo "usage: $0 <version>"
  echo "e.g.: $0 10.1.22"
}

if [ "${version}" = "" ];then
  usage
  exit 1
fi

set -o nounset                              # Treat unset variables as an error

if [ -f ${HOME}/.prep.conf ]; then
    . ${HOME}/.prep.conf
fi

dists="
kvm-rpm-centos6-amd64:centos6-x86_64:rhel/6/x86_64
kvm-rpm-centos6-x86:centos6-i686:rhel/6/i386
kvm-rpm-centos7-amd64:centos7-x86_64:rhel/7/x86_64
kvm-rpm-centos73-amd64:centos73-x86_64:rhel/7.3/x86_64
kvm-rpm-centos73-ppc64:centos73-ppc64:rhel/7.3/ppc64
kvm-rpm-centos73-ppc64le:centos73-ppc64le:rhel/7.3/ppc64le
kvm-rpm-fedora24-amd64:fedora24-x86_64:fedora/24/x86_64
kvm-rpm-fedora24-x86:fedora24-i686:fedora/24/i386
kvm-rpm-fedora25-amd64:fedora25-x86_64:fedora/25/x86_64
kvm-rpm-fedora25-x86:fedora25-i686:fedora/25/i386
kvm-zyp-sles12-amd64:sles12-x86_64:sles/12/x86_64
kvm-zyp-opensuse42-amd64:opensuse42-x86_64:opensuse/42/x86_64
p8-rhel7-rpm-ppc64le:rhel7-ppc64le:rhel/7/ppc64le
p8-rhel7-rpm-ppc64:rhel7-ppc64:rhel/7/ppc64
p8-suse12-rpm-ppc64le:suse12-ppc64le:sles/12/ppc64le
" 
old_dists="
p8-rhel6-rpm-ppc64:rhel6-ppc64:rhel/6/ppc64
kvm-zyp-sles11-amd64:sles11-x86_64:sles/11/x86_64
kvm-zyp-sles11-x86:sles11-i686:sles/11/i386
"

cd ${dir_rpm_shared}

for dist_pair in ${dists}; do
  dist=(${dist_pair//:/ })
  cp -avi ${dir_release}/mariadb-${version}/yum/${dist[2]}/rpms/MariaDB-${version}-${dist[1]}-shared.rpm ./
  if [ -e "mariadb-shared-10.1-${dist[0]}.rpm" ]; then
    rm -v mariadb-shared-10.1-${dist[0]}.rpm
  fi
  ln -sv MariaDB-${version}-${dist[1]}-shared.rpm mariadb-shared-10.1-${dist[0]}.rpm
  echo;echo
done

