#!/bin/bash - 
#===============================================================================
#
#          FILE:  prep-odbc
# 
#         USAGE:  ./prep-odbc <version> <build_dir>
# 
#   DESCRIPTION:  This script is used to prepare files for a MariaDB
#                 Connector/ODBC release
# 
#        AUTHOR: Daniel Bartholomew
#       CREATED: 17/05/23 00:56:37 EST
#===============================================================================


#-------------------------------------------------------------------------------
#  Variables
#-------------------------------------------------------------------------------
version=${1}
dir_build=${2}

dir_name="connector-odbc-${version}"

# set location of prep.conf and prep.log to XDG-compatible directories and then
# create them if they don't exist
dir_conf=${XDG_CONFIG_HOME:-~/.config}
dir_log=${XDG_DATA_HOME:-~/.local/share}


#-------------------------------------------------------------------------------
#  Functions
#-------------------------------------------------------------------------------
sumgen() {
  for sum in md5 sha1 sha256 sha512;do
	echo;LINE;echo ${sum};
	${sum}sum ./mar* >> ${sum}sums.txt
	${sum}sum -c ${sum}sums.txt
  done
  DIV
}

userInput() {
  question="$@"
  echo
  read -p "${question} "
  echo
  INPUT=${REPLY}
  return 0
}

userResponse() {
  question="${@}"
  read -p "${question} " -n 1
  echo
  ANSWER=${REPLY}
  RESPONSE=${REPLY}
  return 0
}

loadDefaults() {
  # Load the paths (if they exist)
  if [ -f ${dir_conf}/prep.conf ]; then
      . ${dir_conf}/prep.conf
  else
    echo
    echo "ERROR: ${dir_conf}/prep.conf preferences file not found"
    echo "Exiting..."
    exit 1
  fi
  if [ -f ${dir_conf}/common ]; then
      . ${dir_conf}/common
  else
    echo "ERROR: ${dir_conf}/common functions file not found"
    echo "Exiting..."
    exit 2
  fi
}

usage() {
  DIV
  echo "usage: $0 <version> <build_dir>"
  echo " e.g.: $0 3.0.1 /ds413/archive/builds/odbc-3.0/e5dd7440815d1ca2f2e96c3c305718fc9b4a8502/"
  echo;LINE
  echo
  exit 1
}

shouldI() {
  local cont
  cont=""
   while [ -z ${cont} ]; do
     userResponse "Should I ${@//_/ }? [y/n]"
     case ${ANSWER} in
      "y")
        ${@}
        cont="yes"
        return 0
        ;;
      "n")
        echo "Skipping . . . "
        cont="yes"
        return 0
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        cont=""
        ;;
    esac
  done
}

copy_win_packages_to_sign-todo_dir() {
  RC cp -avi ${dir_build}/codbc-windows/*.msi ~/sign-todo/
  RC tree ~/sign-todo/
  MSG "Quitting so Win Package signing can occur."
  MSG_L "Re-run script when signing is completed and move signed packages back."
  exit 0
}

move_win_packages_from_sign-done_dir() {
  RC mv -vi ~/sign-done/mariadb-connector-odbc*msi ${dir_build}/codbc-windows/
  RC tree ~/sign-done/
}

verify_signed_win_packages() {
  for msi in ${dir_build}/codbc-windows/*msi ; do
    MSG "Verifying ${msi}"
    RC osslsigncode verify -in ${msi}
  done
}

copy_and_stage_files() {
  #MSG "fixing permissions"

  #for dir in $(sudo -u buildbot find ${dir_build} -type d);do
  #  sudo -u buildbot chmod -c 755 "${dir}"
  #done
  #for file in $(sudo -u buildbot find ${dir_build} -type f);do
  #  sudo -u buildbot chmod -c 644 "${file}"
  #done

  MSG "Copying and staging files"
  pushd ${co_home}
    if [[ ! -d "${dir_name}" ]];then
      mkdir -v ${dir_name}
    fi
    # Linux files
    if cp -avi ${dir_build}/*/*i386.tar.gz ${dir_name}/ ; then
      MSG "Copied Linux x86 files"
    else
      MSG "No Linux x86 files"
    fi
    if cp -avi ${dir_build}/*/*amd64.tar.gz ${dir_name}/ ; then
      MSG "Copied Linux amd64 files"
    else
      MSG "ERROR: Linux amd64 files not found"
      exit 3
    fi
    if cp -avi ${dir_build}/*/*aarch64.tar.gz ${dir_name}/ ; then
      MSG "Copied Linux aarch64 files"
    else
      MSG "ERROR: Linux aarch64 files not found"
      exit 3
    fi
    # Windows files
    if cp -avi ${dir_build}/*/*msi ${dir_name}/ ; then
      MSG "Copied Windows files"
    else
      MSG "ERROR: Windows files not Found"
    fi
    # Mac files
    if cp -avi ${dir_build}/*/*pkg ${dir_name}/;then
      MSG "Copied MacOS files"
    else
      MSG "No MacOS files"
    fi
    # Src files
    cp -avi ${dir_build}/*/*src.zip ${dir_name}/
    cp -avi ${dir_build}/*/*src.tar.gz ${dir_name}/
  popd
  echo;echo;echo
}

prep_org_files() {
  # Prep .org files
  MSG "Prepping org files"
  if [[ ! -d "${co_home_org}/${dir_name}" ]];then
    mkdir -v ${co_home_org}/${dir_name}
  fi
  cp -avi ${co_home}/${dir_name}/*src* ${co_home_org}/${dir_name}/
  pushd ${co_home_org}/${dir_name}
    sumgen
    for file in *;do
      echo "+ gpg ${gpg_opts} ${file}"
              gpg ${gpg_opts} ${file}
    done
  popd
  echo;echo;echo
}

prep_com_files() {
  # Prep .com files
  MSG "Prepping com files"
  pushd ${co_home}/${dir_name}
    sumgen
    for file in *;do
      RC gpg ${ent_gpg_opts} ${file}
    done
  popd
  echo;echo;echo
}

#===  FUNCTION  ================================================================
#          NAME:  uploader
#   DESCRIPTION:  Upload a release
#===============================================================================
uploader() {
  local dest
  local dests
  local rsync_uploader_opts
  dests="$@"
  rsync_uploader_opts="-av --delete-before --exclude=TIME --exclude=exclude --exclude=*orig"
  for dest in ${dests} ; do
    local cont
    cont=""
    while [ -z ${cont} ]; do
      userResponse "Should I upload to ${dest}? [y/n]"
      case ${ANSWER} in
        y)
          MSG "Uploading to ${dest}..."
          case ${dest} in
            *hz-archive*)
              rsync_uploader_opts="${rsync_uploader_opts} --no-group --no-owner --no-perms"
              ;;
          esac
          rsync_wrapper "${rsync_uploader_opts} ${co_home_org}/${dir_name} ${dest}/"
          cont="yes"
          ANSWER=""
          ;;
        n)
          MSG "Skipping uploading to ${dest}..."
          cont="yes"
          ANSWER=""
          ;;
        *)
          MSG_L "Please answer [y]es or [n]o."
          cont=""
          ANSWER=""
          ;;
      esac
    done
  done
}

# Wrapper functions for uploader
upload_to_the_mirrors() {
  uploader "${mirrors}"
}

upload_to_the_archives() {
  uploader "${archives}"
}

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  rsync_wrapper
#   DESCRIPTION:  This function provides a safety net for using rsync. It takes
#                 the options part of the rsync (everything that would come
#                 after the rsync command itself on the command-line) and first
#                 runs it with the --dry-run flag. It then asks if everything
#                 is OK. Assuming things are OK, it runs the rsync for real.
#-------------------------------------------------------------------------------
rsync_wrapper() {
  local upload
  upload=""
  rsync_body="${@}"
  MSG_L "Doing a dry run..."
  RC rsync --dry-run ${rsync_body} | less
  echo
  while [ -z ${upload} ]; do
    userResponse "Did the dry run look OK? [y/n]"
    case ${ANSWER} in
      "y")
        MSG_L "Transferring for real..."
        RC rsync ${rsync_body}
        echo
        upload="yes"
        ANSWER=""
        return 0
        ;;
      "n")
        MSG_L "Something went wrong..."
        ANSWER=""
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}


upload_to_the_primary_mirror() {
  local upload
  upload=""
  echo;echo;echo;
  MSG "Doing a dry-run..."
  echo "+ rsync --dry-run -av --delete-after ${co_home_org}/${dir_name} ${primary_mirror}:data/"
          rsync --dry-run -av --delete-after ${co_home_org}/${dir_name} ${primary_mirror}:data/
  echo;echo;echo
  while [ -z ${upload} ]; do
    userResponse "Does the above look OK? [y/n]"
    case ${ANSWER} in
      "y")
        echo "+ rsync -av --delete-after ${co_home_org}/${dir_name} ${primary_mirror}:data/"
                rsync -av --delete-after ${co_home_org}/${dir_name} ${primary_mirror}:data/
        echo;echo;echo
        upload="yes"
        return 0
        ;;
      "n")
        echo "Something went wrong..."
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}

upload_to_staging() {
  local upload
  upload=""
  echo;echo;echo;
  MSG "Doing a dry-run..."
  echo "+ rsync --dry-run -av --delete-after ${co_home}/${dir_name} ${co_home_corp_staging}/"
          rsync --dry-run -av --delete-after ${co_home}/${dir_name} ${co_home_corp_staging}/
  echo;echo;echo
  while [ -z ${upload} ]; do
    userResponse "Does the above look OK? [y/n]"
    case ${ANSWER} in
      "y")
        echo "+ rsync -av --delete-after ${co_home}/${dir_name} ${co_home_corp_staging}/"
                rsync -av --delete-after ${co_home}/${dir_name} ${co_home_corp_staging}/
        echo;echo;echo
        upload="yes"
        return 0
        ;;
      "n")
        echo "Something went wrong..."
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}


upload_to_prod() {
  local upload
  upload=""
  echo;echo;echo;
  MSG "Doing a dry-run..."
  echo "+ rsync --dry-run -av --delete-after ${co_home}/${dir_name} ${co_home_corp}/"
          rsync --dry-run -av --delete-after ${co_home}/${dir_name} ${co_home_corp}/
  echo;echo;echo
  while [ -z ${upload} ]; do
    userResponse "Does the above look OK? [y/n]"
    case ${ANSWER} in
      "y")
        echo "+ rsync -av --delete-after ${co_home}/${dir_name} ${co_home_corp}/"
                rsync -av --delete-after ${co_home}/${dir_name} ${co_home_corp}/
        echo;echo;echo
        upload="yes"
        return 0
        ;;
      "n")
        echo "Something went wrong..."
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        upload=""
        ;;
    esac
  done
}

#===  FUNCTION  ================================================================
#          NAME:  remove_a_dir_from_the_local_mirror_dir
#   DESCRIPTION:  This function displays the dirs in the ${dir_local_mirror}
#                 directory and prompts for a dir to release, repeating until
#                 you answer 'n'.
#===============================================================================
remove_a_dir_from_the_local_mirror_dir() {
  local done_removing
  done_removing=""
  while [ -z ${done_removing} ];do
    MSG "Releases currently in ${dir_local_mirror}"
    tree -L 1 ${dir_local_mirror}
    LINE
    userInput "What release should I remove? (e.g. mariadb-10.6.7, s to stop)"
    release_to_remove="${INPUT}"
    if [ -z ${release_to_remove} ] ; then
      MSG "Please enter a release or 's' to stop."
    else
      case ${release_to_remove} in
        s)
          MSG_L "Stopping..."
          done_removing='yes'
          ;;
        *)
          if [ -d ${dir_local_mirror}/${release_to_remove} ] ; then
            userResponse "Ok to remove ${release_to_remove}? [y/n]"
            case ${ANSWER} in
              y)
                MSG_L "Removing ${release_to_remove}..."
                RC rm -rf ${dir_local_mirror}/${release_to_remove}
                ;;
              n)
                MSG_L "Not removing ${release_to_remove}"
                ;;
              *)
                MSG_L "Please answer [y]es or [n]o."
                ;;
            esac
          else
            MSG_L "${release_to_remove} doesn't appear to exist, please try again."
            PAUSE
          fi
          done_removing=""
          ;;
      esac
    fi
  done
}

#===  FUNCTION  ================================================================
#          NAME:  copy_the_release_to_the_local_mirror_dir
#   DESCRIPTION:  Copy the release to the local mirror prep directory
#===============================================================================
copy_the_release_to_the_local_mirror_dir() {
  if [[ -d ${dir_local_mirror}/${dir_name} ]] ; then
    MSG_L "Found existing ${dir_name} under ${dir_local_mirror}/, not copying..."
  else
    RC cp -ail ${co_home_org}/${dir_name} ${dir_local_mirror}/
  fi
  verify_local_mirror_copy_is_good
}

verify_local_mirror_copy_is_good() {
  local dry_run_status
  dry_run_status=""
  MSG "Doing an rsync dry-run to verify the local mirror copy is good"
  MSG_L "If rsync doesn't find anything to sync then the copy is good."
  for dir in ${dir_name} ; do
    RC rsync --dry-run -avP ${co_home_org}/${dir} ${dir_local_mirror}/
    LINE
  done
  while [ -z ${dry_run_status} ]; do
    userResponse "Did the dry run look OK? [y/n]"
    case ${ANSWER} in
      "y")
        MSG_L "Local mirror copy is good..."
        dry_run_status="yes"
        ANSWER=""
        return 0
        ;;
      "n")
        MSG_L "Local mirror copy is not good. Something went wrong..."
        MSG_L "You might want to delete the local mirror copy and re-run this step"
        ANSWER=""
        exit 1
        ;;
      *)
        echo "Please answer [y]es or [n]o."
        echo
        dry_run_status=""
        ;;
    esac
  done
}



#===  FUNCTION  ================================================================
#          NAME:  generate_the_file_list_pickle_for_org_downloads
#   DESCRIPTION:  This function logs in to the primary mirror and runs the
#                 command to generate the pickle that is then imported into the
#                 mariadb.org downloads system.
#===============================================================================
generate_the_file_list_pickle_for_org_downloads() {
  ssh -t -t ${primary_mirror} "set -x; python generate_file_list.py data/ --release=${dir_name}";
}

update_the_STATUS_file() {
  echo "+ date +%s > ${co_home_org}/STATUS"
          date +%s > ${co_home_org}/STATUS
  MSG "STATUS file updated"
}

#-------------------------------------------------------------------------------
# Main Script
#-------------------------------------------------------------------------------

loadDefaults

case ${version} in
  ""|"-h") usage
    ;;
esac

set -eu
  # -e  Exit immediately if a simple command exits with a non-zero status,
  #     unless the command that fails is part of an until or  while loop, part
  #     of an if statement, part of a && or || list, or if the command's return
  #     status is being inverted using !.  -o errexit
  #
  # -u  Treat unset variables as an error when performing parameter expansion.
  #     An error message will be written to the standard error, and a
  #     non-interactive shell will exit.
  #
  # -x  Print a trace of simple commands and their arguments after they are
  #     expanded and before they are executed.

MSG_I "Preparing MariaDB Connector/ODBC ${version} release..."
echo;echo
shouldI copy_win_packages_to_sign-todo_dir
echo;echo
shouldI move_win_packages_from_sign-done_dir
echo;echo
verify_signed_win_packages
echo;echo
shouldI copy_and_stage_files
echo;echo
shouldI prep_org_files
echo;echo
shouldI prep_com_files
echo;echo
shouldI upload_to_staging
echo;echo
shouldI upload_to_prod
echo;echo

MSG_I "Mirrors"
for mirror in ${mirrors} ; do echo "- ${mirror}";done;echo
shouldI upload_to_the_mirrors
echo;echo
MSG_I "Archives"
for archive in ${archives} ; do echo "- ${archive}";done;echo
shouldI upload_to_the_archives
echo;echo

shouldI copy_the_release_to_the_local_mirror_dir
shouldI remove_a_dir_from_the_local_mirror_dir

echo;echo
MSG_I "+ All done!"
LINE;LINE;LINE
echo;echo;echo

