version: '3'
x-common-variables: &common-variables
  MARIADB_USER: monitor
  MARIADB_PASSWORD: password
  MARIADB_DATABASE: testdb
  MARIADB_RANDOM_ROOT_PASSWORD: 1

x-common-attributes: &common-attributes
  build:
    context: .
  environment: *common-variables
  healthcheck:
    test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    start_period: 10s
    interval: 10s
    timeout: 5s
    retries: 3

services:
  master:
    <<: *common-attributes
    hostname: master
    volumes:
      - 'master:/var/lib/mysql'
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy

  node1:
    <<: *common-attributes
    volumes:
      - 'node1:/var/lib/mysql'

  node2:
    <<: *common-attributes
    volumes:
      - 'node2:/var/lib/mysql'

volumes:
  master:
    driver: local
  node1:
    driver: local
  node2:
    driver: local

